variable "rg_Name" { type = string }
variable "location" { type = string }
variable "pip_allocation" { type = string }
variable "vm_nic" { type = string }
variable "ip_configuration" { type = string }
variable "vm_name" { type = string }
variable "vm_size" { type = string }
variable "vm_username" { type = string }
variable "vm_password" { type = string }
variable "vm_image_publisher" { type = string }
variable "vm_image_offer" { type = string }
variable "vm_image_sku" { type = string }
variable "vm_image_version" { type = string }
variable "vm_os_disk_strg_type" { type = string }
variable "vm_os_disk_caching" { type = string }
variable "vm_subnetid" { type = string }
variable "use_gallery_image" { type = bool }
variable "image_defination_id" { type = string }

# ✅ Added variable for NSG association
variable "nsg_id" { type = string }
